export const images = {
  WHATSAPP_BG: require('../assets/Images/Whtasapp_BG.jpg'),
  EYE_OPEN: require('../assets/Images/eyeOpen/eyeOpen.png'),
  EYE_CLOSE: require('../assets/Images/eyeClosed/eyeClose.png'),
  CHATS: require('../assets/Images/chatIcon/chatIcon.png'),
  SETTINGS: require('../assets/Images/settings/settings.png'),
  HOMEICON: require('../assets/Images/homeIcon/homeIcon.png'),
  USERICON: require('../assets/Images/userIcon/userIcon.png'),
  BACK_ICON: require('../assets/Images/backIcon/backIcon.png'),
  WHATSAPP_LOGO: require('../assets/Images/whatsappTwoBg/whatsapp-logo.png'),
  COMMUNITY_ICON: require('../assets/Images/communtyIcon/community-img.png'),
  USER_ONE: require('../assets/Images/userOne/user1.jpeg'),
  USER_TWO: require('../assets/Images/userTwo/user2.jpeg'),
  USER_THREE: require('../assets/Images/userThree/user3.jpeg'),
  USER_FOUR: require('../assets/Images/userFour/user4.jpeg'),
  USER_FIVE: require('../assets/Images/userFive/user5.jpeg'),
  USER_SIX: require('../assets/Images/userSix/user6.jpeg'),
  USER_SEVEN: require('../assets/Images/userSeven/user7.jpeg'),
  USER_EIGHT: require('../assets/Images/userEight/user8.jpeg'),
  USER_NINE: require('../assets/Images/userNine/user9.jpeg'),
  USER_TEN: require('../assets/Images/userTen/user10.jpeg'),
  USER_ELEVEN: require('../assets/Images/userEleven/user11.jpeg'),
};
