export enum RouteName {
  LOGIN = 'login',
  SPLASH_SCREEN = 'splashScreen',
  SIGNUP = 'signup',
  DASHBOARD = 'dashboard',
  USER_SCREEN = 'userScreen',
  SETTINGS = 'settings',
  BOTTOM_TAB_NAVIGATOR = 'bottomTabNavigation',
  CHAT_SCREEN = 'chatScreen',
  USER_STACK = 'userStack',
  COMMUNITY_SCREEN = 'communityScreen',
  HOMESCREEN = 'homeScreen',
  CHAT_LIST = 'chatList',
  CALL_LIST = 'callList',
  STATUS_LIST = 'statusList',
}
