export enum RouteName {
  LOGIN = 'login',
  SPLASH_SCREEN = 'splashScreen',
  SIGNUP = 'signup',
  DASHBOARD = 'dashboard',
  USER_SCREEN = 'userScreen',
  SETTINGS = 'settings',
  BOTTOM_TAB_NAVIGATOR = 'bottomTabNavigation',
  CHAT_SCREEN = 'chatScreen',
  USER_STACK = 'userStack',
  COMMUNITY_SCREEN = 'community',
  HOMESCREEN = 'homeScreen',
  CHATS = 'CHATS',
  CALLS = 'CALLS',
  STATUS = 'STATUS',
  COMMUNITY = 'COMMUNITY',
  WPCHATSCREEN = 'wpChatScreen',
}
